# -*- coding: utf-8 -*-
"""modelameliore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13_pq6stBQkWQ54AtRU60_40EX7oB0mSa
"""
from sklearn.preprocessing import MinMaxScaler
import joblib # For saving/loading the scaler
import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from database import get_engine
import torch


# ====================== 1. CHARGEMENT ET NETTOYAGE ======================
print("Chargement du fichier...")
query = "SELECT * FROM fact_transactions" # Assurez-vous que cette table existe et contient une colonne 'date_heure'
engine = get_engine()
df = pd.read_sql(query, engine)
print(f"✅ Fichier chargé : {len(df)} lignes")
# On ne garde QUE la colonne date_heure pour ce modèle de prédiction du nombre de voitures par heure
df = df[['date_heure']].copy()

# Conversion en datetime
df['date_heure'] = pd.to_datetime(df['date_heure'])

# Création du nombre de voitures par heure (comptage des passages)
hourly = df.resample('h', on='date_heure').size().reset_index(name='nombre_voitures')

# On met la date comme index
hourly.set_index('date_heure', inplace=True)

print(f"✅ Données préparées : {len(hourly)} heures")
print(f"Période : de {hourly.index.min()} à {hourly.index.max()}")
print("\nAperçu :")
print(hourly.head(10))

# ====================== 2. PRÉPARATION POUR LSTM ======================
values = hourly['nombre_voitures'].values.reshape(-1, 1)

# Normalisation entre 0 et 1
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(values)

# Paramètres
lookback = 168          # 7 jours d'historique (recommandé)
train_ratio = 0.8

# Création des séquences
def create_sequences(data, lookback):
    X, y = [], []
    for i in range(len(data) - lookback):
        X.append(data[i:i + lookback])
        y.append(data[i + lookback])
    return np.array(X), np.array(y)

X, y = create_sequences(scaled_data, lookback)

# Split train/test
train_size = int(len(X) * train_ratio)
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

# Conversion en tenseurs PyTorch
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

print(f"\nForme des données :")
print(f"X_train : {X_train.shape} | y_train : {y_train.shape}")

# ====================== 3. Dataset & Model (identique) ======================
class TimeSeriesDataset(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y
    def __len__(self):
        return len(self.X)
    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

train_dataset = TimeSeriesDataset(X_train, y_train)
test_dataset = TimeSeriesDataset(X_test, y_test)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

class LSTMModel(nn.Module):
    def __init__(self, hidden_size=64, num_layers=2):
        super().__init__()
        self.lstm = nn.LSTM(input_size=1, hidden_size=hidden_size,
                           num_layers=num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        return self.fc(lstm_out[:, -1, :])

model = LSTMModel()
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

# ====================== 4. Entraînement ======================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print("\nEntraînement du modèle LSTM...")
epochs = 25

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)

        optimizer.zero_grad()
        output = model(batch_x)
        loss = criterion(output, batch_y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    if (epoch + 1) % 5 == 0 or epoch == 0:
        print(f"Epoch {epoch+1}/{epochs} - Loss: {total_loss/len(train_loader):.6f}")

# ====================== 5. Évaluation & Graphique ======================
model.eval()
predictions = []
with torch.no_grad():
    for batch_x, _ in test_loader:
        batch_x = batch_x.to(device)
        pred = model(batch_x).cpu().numpy()
        predictions.append(pred)

predictions = np.concatenate(predictions)
predictions = scaler.inverse_transform(predictions)
y_test_real = scaler.inverse_transform(y_test.numpy())

# Métriques
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_test_real, predictions)
rmse = np.sqrt(mean_squared_error(y_test_real, predictions))

print(f"\n✅ Résultats sur le test :")
print(f"MAE  : {mae:.2f} voitures par heure")
print(f"RMSE : {rmse:.2f} voitures par heure")

# Graphique
plt.figure(figsize=(15, 7))
plt.plot(hourly.index[-len(y_test_real):], y_test_real, label="Réel", linewidth=2)
plt.plot(hourly.index[-len(predictions):], predictions, label="Prédiction LSTM", linewidth=2)
plt.title("Prédiction du nombre de voitures par heure (Modèle simplifié)")
plt.xlabel("Date")
plt.ylabel("Nombre de voitures par heure")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Sauvegarde
torch.save(model.state_dict(), "lstm_voitures_par_heure_simplifie.pth")
print("\nModèle sauvegardé !")



# It's crucial to redefine the model class exactly as it was defined
# when the model was saved. We'll grab the definition from the previous cell.
class LSTMModel(nn.Module):
    def __init__(self, hidden_size=64, num_layers=2):
        super().__init__()
        self.lstm = nn.LSTM(input_size=1, hidden_size=hidden_size,
                           num_layers=num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        lstm_out, _ = self.lstm(x)
        return self.fc(lstm_out[:, -1, :])

# --- 1. Load the Model ---
model = LSTMModel() # Instantiate the model with the same architecture
model.load_state_dict(torch.load("lstm_voitures_par_heure_simplifie.pth"))
model.eval() # Set the model to evaluation mode

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print("✅ Modèle LSTM chargé avec succès pour de nouvelles prédictions.")

# --- 2. Préparer les données pour la prédiction ---
# Nous avons besoin des dernières 'lookback' observations pour initialiser la prédiction.
# 'scaled_data', 'lookback', 'scaler' et 'hourly' sont disponibles depuis la cellule précédente.

# Assurez-vous que 'scaled_data' est disponible (exécutée dans la cellule précédente)
if 'scaled_data' not in globals() or 'lookback' not in globals() or 'scaler' not in globals() or 'hourly' not in globals():
    print("Erreur : Les variables 'scaled_data', 'lookback', 'scaler' ou 'hourly' ne sont pas définies. Veuillez exécuter la cellule d'entraînement complète d'abord.")
else:
    # Prendre les 'lookback' dernières observations comme séquence d'entrée
    last_sequence = scaled_data[-lookback:]

    # Convertir en tenseur PyTorch et ajouter une dimension de batch
    input_sequence = torch.tensor(last_sequence, dtype=torch.float32).unsqueeze(0).to(device)

    # --- 3. Générer les prédictions pour la semaine prochaine (168 heures) avec variation ---
    future_predictions_scaled = []
    num_future_steps = 168 # 7 jours * 24 heures
    noise_std_dev = 0.8 # Standard deviation for the noise, adjust as needed

    print(f"Génération des prédictions pour les {num_future_steps} prochaines heures avec variation...")

    with torch.no_grad():
        for _ in range(num_future_steps):
            predicted_value = model(input_sequence)

            # Store the 'clean' prediction for plotting
            future_predictions_scaled.append(predicted_value.item())

            # Add a small amount of random Gaussian noise to the predicted value
            # before feeding it back into the sequence. This simulates real-world
            # variation and prevents the predictions from becoming too smooth.
            noise = torch.randn(predicted_value.shape).to(device) * noise_std_dev

            # Ensure the noisy predicted value stays within the [0, 1] range after adding noise
            noisy_predicted_value = torch.clamp(predicted_value + noise, 0, 1)

            # Update the input sequence for the next prediction with the noisy value
            noisy_predicted_value_tensor = noisy_predicted_value.unsqueeze(-1) # Reshape to (1, 1, 1)
            input_sequence = torch.cat((input_sequence[:, 1:, :], noisy_predicted_value_tensor), dim=1)

    # --- 4. Inverse-transformer les prédictions ---
    future_predictions = scaler.inverse_transform(np.array(future_predictions_scaled).reshape(-1, 1))

    print(f"✅ Nouvelles prédictions générées : {len(future_predictions)} points.")

    # --- 5. Préparer l'index temporel pour les prédictions ---
    last_timestamp = hourly.index[-1]
    future_dates = pd.date_range(start=last_timestamp + pd.Timedelta(hours=1), periods=num_future_steps, freq='h')

    # --- 6. Visualiser les prédictions ---
    plt.figure(figsize=(18, 8))

    # Plot les données historiques récentes (par exemple, les 4 dernières semaines)
    historical_plot_points = 4 * 7 * 24 # 4 semaines d'heures
    plt.plot(hourly.index[-historical_plot_points:], hourly['nombre_voitures'].tail(historical_plot_points),
             label="Historique (Réel)", color='blue', alpha=0.7)

    # Plot les nouvelles prédictions
    plt.plot(future_dates, future_predictions, label="Nouvelles Prédictions LSTM (Avec Variation)", color='red', linestyle='--')

    plt.title("Prédiction du nombre de voitures par heure (Modèle simplifié)")
    plt.xlabel("Date")
    plt.ylabel("Nombre de voitures par heure")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    print("Aperçu des nouvelles prédictions pour la semaine prochaine :")
    future_df = pd.DataFrame(future_predictions, index=future_dates, columns=['Prédiction_Voitures_Avec_Variation'])
    print(future_df.head())
    print(future_df.tail())


try:
    joblib.dump(scaler, 'min_max_scaler.pkl')
    with open('lookback.txt', 'w') as f:
        f.write(str(lookback))
    print("✅ Scaler and lookback value saved: 'min_max_scaler.pkl' and 'lookback.txt'")
except NameError:
    print("Error: 'scaler' or 'lookback' not found. Please ensure the training cell was run.")
    print("Cannot proceed with FastAPI setup without these components.")
    # Exit or provide placeholder if this block was designed to be run independently
    # For this Colab context, we assume the previous cells ran successfully.
    raise
